'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace WebApplication1

    Public Partial Class Category

        Public Property CategoryID As Integer

        Public Property CategoryName As String

        Public Property Description As String

        Public Property Picture As Byte()

        Public Property Test As String

        Public Property Te3st2 As String
    End Class
End Namespace
